# Configurações do Banco de Dados (Neon)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Brapi Config
brapi.token=${BRAPI_TOKEN}
# Lista de tickers para monitorar (exemplo)
fii.tickers=MXRF11,HGLG11,VISC11,BTLG11,KNIP11,KNCR11,IRDM11,CPTS11,XPLG11,XPML11,VILG11,BARI11,RECR11,HGRU11,VRTA11,BCFF11,TRXF11,HGBS11,VGHF11,MALL11,JSRE11,ALZR11,GARE11,TGAR11,KNSC11,RBRR11,DEVA11,URPR11,HSAF11,HCTR11,TORD11,VSLH11,GALG11,BRCO11,RBRF11,PVBI11,VCJR11,SARE11,BBRC11,CACR11,CVBI11,FEXC11,FIIB11,GTWR11,HABT11,HGPO11,MCCI11,OUJP11,RBRY11,RBVA11,RECT11,RZAK11,TEPP11,VINO11,XPIN11
