# Configurações do Banco de Dados (Neon)
spring.datasource.url=jdbc:postgresql://ep-square-math-acq7j1zp-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Brapi Config
brapi.token=${BRAPI_TOKEN}
# Lista de tickers para monitorar (exemplo)
fii.tickers=MXRF11,HGLG11,VISC11,BTLG11,KNIP11
